name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2021-07-07
version: '9.2.1'
project: 'drupal'
datestamp: 1625664353
